import { GetStaticProps } from "next";
import Head from "next/head";
import Layout from "../components/layout";
import { DATABASE_ID, TOKEN } from "../config";

const Project = ({ projectNames }: { projectNames: string[] }) => {
  return (
    <Layout>
      <h1>{projectNames}</h1>
      <Head>
        <title>정하승의 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Layout>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const options = {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Notion-Version": "2022-06-28",
      "Content-Type": "application/json",
      Authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({ page_size: 100 }),
  };

  const response = await fetch(`https://api.notion.com/v1/databases/${DATABASE_ID}/query`, options);
  const projects = await response.json();

  const projectNames = projects.results.map(
    (project: any) => project.properties["이름"].title[0].plain_text
  );

  return {
    props: { projectNames },
  };
};

export default Project;
